### PR TITLE
Leading zeros and "-0" fix

### PR DESCRIPTION
**Pull request by Guiorgy**
added preventLeadingZeroes (leading zeros are those: **00**_12.3600_) that will prevent the user from inputting leading zeroes.

also fixed "-0", example: -0.2 erasing once leaves "-0"

### CODE REVIEW

**Comment by maltaisn** [comment]
Thanks for fixing this I hadn't thought of it! But do you think there is a reason to allow leading zeroes, when would anyone want that?

**Comment by Guiorgy** [comment]
@maltaisn , counter question: Do you think there is a reason to allow trailing zeros? :)

My answer on your question is probably no, so if you want I'll change that...

**Comment by maltaisn** [comment]
That's exactly what I thought so I'll probably remove both. That shouldn't cause issues for anyone because I don't think anyone currently shows trailing zeroes.

**Comment by Guiorgy** [comment]
@maltaisn , here you go. Hope this is what you wanted.

**Comment by maltaisn** [comment]
Yes exactly thanks. I'll merge it shortly.

**Comment by maltaisn** [comment]
This was changed in v1.3.0

**Comment by Guiorgy** [comment]
@maltaisn , also don't forget to remove **setStripTrailingZeroes(boolean strip)** from **Calculator settings** in the wiki.

**Comment by maltaisn** [comment]
Good catch, I removed it, thanks.

**Comment by mirinas** [comment]
Correct me if i'm wrong, but doesn't trailing zeroes disabled will make typing values like 1,0001 impossible?

**Comment by Guiorgy** [comment]
@Sosig77 , if I am not wrong, zeros are **stripped** when returning the result (meaning at the end of calculations, so it should be fine. Unlike that, what I did was **prevent** the user from typing leading zeros so you can't type something like 001.0001

I did just test the calc, I typed 1.0000100, result is 1.00001, seems to be working to me...

**EDIT** here're screenshots:

screenshot_1537451988
screenshot_1537451994

**Comment by mirinas** [comment]
@Guiorgy now it makes sense, i somehow misunderstood it from example in the main pull request.

**Pull request merged**
