### PR TITLE
added hebrew translation

### PR DESCRIPTION
**Pull request by roiAttia**

### CODE REVIEW

**Comment by maltaisn** [comment]
Thanks!

**Comment by roiAttia** [comment]
Hi! first of all, great SDK!
about RTL layout, I think it would be better and more correct if it didnt
support RTL because when it does all the layout gets flipped to the other
side. Iv'e added screenshots with both options to compare.

‫בתאריך יום ו׳, 20 בספט׳ 2019 ב-1:51 מאת ‪maltaisn‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by maltaisn** [comment]
Yes you're right. Most calculator apps have the same layout with RTL so I guess RTL should have no effect for the dialog too.

**Comment by maltaisn** [comment]
I disabled RTL layout in v2.1.1.

**Pull request merged**
